[package]
name = "obsidian-scheduler"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Obsidian-Minecraft-Server-Portal/scheduler.git"
description = "A simple asyncronous scheduling system"


[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.64"
chrono = "0.4.19"
lazy_static = "1.5.0"